# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaEkran(object):
    def setupUi(self, AnaEkran):
        AnaEkran.setObjectName("AnaEkran")
        AnaEkran.resize(800, 600)
        self.AnaForm = QtWidgets.QWidget(AnaEkran)
        self.AnaForm.setObjectName("AnaForm")
        AnaEkran.setCentralWidget(self.AnaForm)
        self.menubar = QtWidgets.QMenuBar(AnaEkran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuKitap_Listesi = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Listesi.setObjectName("menuKitap_Listesi")
        self.menuKitap_Ekle = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Ekle.setObjectName("menuKitap_Ekle")
        self.menuKitap_Guncelle = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.menuKitap_Guncelle.setFont(font)
        self.menuKitap_Guncelle.setObjectName("menuKitap_Guncelle")
        self.menuSil = QtWidgets.QMenu(self.menubar)
        self.menuSil.setObjectName("menuSil")
        self.menu_Cikis = QtWidgets.QMenu(self.menubar)
        self.menu_Cikis.setObjectName("menu_Cikis")
        AnaEkran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnaEkran)
        self.statusbar.setObjectName("statusbar")
        AnaEkran.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuKitap_Listesi.menuAction())
        self.menubar.addAction(self.menuKitap_Ekle.menuAction())
        self.menubar.addAction(self.menuKitap_Guncelle.menuAction())
        self.menubar.addAction(self.menuSil.menuAction())
        self.menubar.addAction(self.menu_Cikis.menuAction())

        self.retranslateUi(AnaEkran)
        QtCore.QMetaObject.connectSlotsByName(AnaEkran)

    def retranslateUi(self, AnaEkran):
        _translate = QtCore.QCoreApplication.translate
        AnaEkran.setWindowTitle(_translate("AnaEkran", "MainWindow"))
        self.menuKitap_Listesi.setTitle(_translate("AnaEkran", "Kitap Listesi"))
        self.menuKitap_Ekle.setTitle(_translate("AnaEkran", "Kitap Ekle"))
        self.menuKitap_Guncelle.setTitle(_translate("AnaEkran", "Kitap Güncelle"))
        self.menuSil.setTitle(_translate("AnaEkran", "Sil"))
        self.menu_Cikis.setTitle(_translate("AnaEkran", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnaEkran = QtWidgets.QMainWindow()
    ui = Ui_AnaEkran()
    ui.setupUi(AnaEkran)
    AnaEkran.show()
    sys.exit(app.exec_())
