# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, Giris):
        Giris.setObjectName("Giris")
        Giris.resize(400, 300)
        self.GirisButonu = QtWidgets.QPushButton(Giris)
        self.GirisButonu.setGeometry(QtCore.QRect(140, 150, 75, 23))
        self.GirisButonu.setObjectName("GirisButonu")
        self.label = QtWidgets.QLabel(Giris)
        self.label.setGeometry(QtCore.QRect(50, 50, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Giris)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 121, 16))
        self.label_2.setObjectName("label_2")
        self.mesajLabel = QtWidgets.QLabel(Giris)
        self.mesajLabel.setGeometry(QtCore.QRect(90, 210, 181, 16))
        self.mesajLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mesajLabel.setObjectName("mesajLabel")
        self.epostaText = QtWidgets.QLineEdit(Giris)
        self.epostaText.setGeometry(QtCore.QRect(220, 50, 113, 20))
        self.epostaText.setObjectName("epostaText")
        self.sifreText = QtWidgets.QLineEdit(Giris)
        self.sifreText.setGeometry(QtCore.QRect(220, 90, 113, 20))
        self.sifreText.setObjectName("sifreText")

        self.retranslateUi(Giris)
        QtCore.QMetaObject.connectSlotsByName(Giris)

    def retranslateUi(self, Giris):
        _translate = QtCore.QCoreApplication.translate
        Giris.setWindowTitle(_translate("Giris", "Form"))
        self.GirisButonu.setText(_translate("Giris", "Giris"))
        self.label.setText(_translate("Giris", "Eposta:"))
        self.label_2.setText(_translate("Giris", "Sifre"))
        self.mesajLabel.setText(_translate("Giris", "Mesaj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Giris = QtWidgets.QWidget()
    ui = Ui_Giris()
    ui.setupUi(Giris)
    Giris.show()
    sys.exit(app.exec_())
