# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anaekran(object):
    def setupUi(self, Anaekran):
        Anaekran.setObjectName("Anaekran")
        Anaekran.resize(400, 300)
        self.A_Button = QtWidgets.QPushButton(Anaekran)
        self.A_Button.setGeometry(QtCore.QRect(160, 50, 75, 23))
        self.A_Button.setObjectName("A_Button")
        self.C_Label = QtWidgets.QLabel(Anaekran)
        self.C_Label.setGeometry(QtCore.QRect(180, 140, 47, 14))
        self.C_Label.setObjectName("C_Label")
        self.buton2 = QtWidgets.QPushButton(Anaekran)
        self.buton2.setGeometry(QtCore.QRect(270, 50, 75, 23))
        self.buton2.setObjectName("buton2")

        self.retranslateUi(Anaekran)
        QtCore.QMetaObject.connectSlotsByName(Anaekran)

    def retranslateUi(self, Anaekran):
        _translate = QtCore.QCoreApplication.translate
        Anaekran.setWindowTitle(_translate("Anaekran", "Form"))
        self.A_Button.setText(_translate("Anaekran", "PushButton"))
        self.C_Label.setText(_translate("Anaekran", "TextLabel"))
        self.buton2.setText(_translate("Anaekran", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Anaekran = QtWidgets.QWidget()
    ui = Ui_Anaekran()
    ui.setupUi(Anaekran)
    Anaekran.show()
    sys.exit(app.exec_())
