import math
a = math.cos(30)
print(a)
print(dir(math))
print(math.factorial(5))
derece = math.degrees(90)
print(math.cos(derece))
print(help(math))
print(math.pow(5,6))
print(help(math.cos))
print(math.sqrt(16))
